from django.db import models
    
class AdmissionForm(models.Model):
    patientFname = models.CharField(max_length=240, blank=True, default='')
    patientLname = models.CharField(max_length=240, blank=True, default='')
    
    weight = models.CharField(max_length=240, blank=True, default='')
    height = models.CharField(max_length=240, blank=True, default='')
    
    medDrug1 = models.CharField(max_length=240, blank=True, default='')
    medDosage1 = models.CharField(max_length=240, blank=True, default='')
    medMorning1 = models.BooleanField(default=False)
    medNoon1 = models.BooleanField(default=False)
    medEvening1 = models.BooleanField(default=False)
    medNight1 = models.BooleanField(default=False)
    
    medDrug2 = models.CharField(max_length=240, blank=True, default='')
    medDosage2 = models.CharField(max_length=240, blank=True, default='')
    medMorning2 = models.BooleanField(default=False)
    medNoon2 = models.BooleanField(default=False)
    medEvening2 = models.BooleanField(default=False)
    medNight2 = models.BooleanField(default=False)
    
    medDrug3 = models.CharField(max_length=240, blank=True, default='')
    medDosage3 = models.CharField(max_length=240, blank=True, default='')
    medMorning3 = models.BooleanField(default=False)
    medNoon3 = models.BooleanField(default=False)
    medEvening3 = models.BooleanField(default=False)
    medNight3 = models.BooleanField(default=False)
    
    liveAloneNo = models.BooleanField(default=False)
    liveAloneYes = models.BooleanField(default=False)
    liveAloneLift = models.BooleanField(default=False)
    liveAloneFloor = models.CharField(max_length=240, blank=True, default='')
    obliationsNo = models.BooleanField(default=False)
    obliationsYes = models.BooleanField(default=False)
        
    relativeSurname1 = models.CharField(max_length=100, blank=True, default='')
    relativeFname1 = models.CharField(max_length=100, blank=True, default='')
    relativePhone1 = models.CharField(max_length=20, blank=True, default='')
    relativeRel1 = models.CharField(max_length=100, blank=True, default='')
    
    relativeSurname2 = models.CharField(max_length=100, blank=True, default='')
    relativeFname2 = models.CharField(max_length=100, blank=True, default='')
    relativePhone2 = models.CharField(max_length=20, blank=True, default='')
    relativeRel2 = models.CharField(max_length=100, blank=True, default='')
    
    relativeSurname3 = models.CharField(max_length=100, blank=True, default='')
    relativeFname3 = models.CharField(max_length=100, blank=True, default='')
    relativePhone3 = models.CharField(max_length=20, blank=True, default='')
    relativeRel3 = models.CharField(max_length=100, blank=True, default='')
    
    careNo = models.BooleanField(default=False)
    careYes = models.BooleanField(default=False)
    careDegree1 = models.BooleanField(default=False)
    careDegree2 = models.BooleanField(default=False)
    careDegree3 = models.BooleanField(default=False)
    careDegree4 = models.BooleanField(default=False)
    careDegree5 = models.BooleanField(default=False)
    
    hospitalizedNo = models.BooleanField(max_length=100, blank=True, default='')
    hospitalizedYes = models.BooleanField(max_length=100, blank=True, default='')
    hospAbroadPlace = models.CharField(max_length=100, blank=True, default='')
    hospAbroadTime = models.CharField(max_length=100, blank=True, default='')
    
    commNoImpairment = models.BooleanField(default=False)
    commForeignLang = models.BooleanField(default=False)
    commForeignLangYes = models.BooleanField(default=False)
    commForeignLangNo = models.BooleanField(default=False)
    commSignLang = models.BooleanField(default=False)
    commDisorder = models.BooleanField(default=False)
    commTrach = models.BooleanField(default=False)
    
    visionLeft = models.BooleanField(default=False)
    visionRight = models.BooleanField(default=False)
    blindnessLeft = models.BooleanField(default=False)
    blindnessRight = models.BooleanField(default=False)
    visualAidLeft = models.BooleanField(default=False)
    visualAidRight = models.BooleanField(default=False)
    
    hearingNoImp = models.BooleanField(default=False)
    hearingAidRight = models.BooleanField(default=False)
    hearingAidLeft = models.BooleanField(default=False)
    hearingHardRight = models.BooleanField(default=False)
    hearingHardLeft = models.BooleanField(default=False)
    deafnessRight = models.BooleanField(default=False)
    deafnessLeft = models.BooleanField(default=False)
    
    disorNoImp = models.BooleanField(default=False)
    disorTime = models.BooleanField(default=False)
    disorPlace = models.BooleanField(default=False)
    disorPerson = models.BooleanField(default=False)
    
    understNoImp = models.BooleanField(default=False)
    understConfusion = models.BooleanField(default=False)
    understNerv = models.BooleanField(default=False)
    understAltered = models.BooleanField(default=False)
    
    disabilityNo = models.BooleanField(default=False)
    disabilityYes = models.BooleanField(default=False)
    disabilityHemiYes = models.BooleanField(default=False)
    disabilityHemi = models.CharField(max_length=240, blank=True, default='')
    disabilityAmputYes = models.BooleanField(default=False)
    disabilityAmput = models.CharField(max_length=240, blank=True, default='')
    disabilityParaYes = models.BooleanField(default=False)
    disabilityPara = models.CharField(max_length=240, blank=True, default='')
    disabilityTetraYes = models.BooleanField(default=False)
    disabilityTetra = models.CharField(max_length=240, blank=True, default='')
    disabilityLimbsYes = models.BooleanField(default=False)
    disabilityLimbs = models.CharField(max_length=240, blank=True, default='')
    disabilityMisalYes = models.BooleanField(default=False)
    disabilityMisal = models.CharField(max_length=240, blank=True, default='')
    disabilityProYes = models.BooleanField(default=False)
    disabilityProNo = models.BooleanField(default=False)
    
    sleepNoImp = models.BooleanField(default=False)
    sleepDiff = models.BooleanField(default=False)
    sleepBreath = models.BooleanField(default=False)
    
    dietWhole = models.BooleanField(default=False)
    dietNoSugar = models.BooleanField(default=False)
    dietVeg = models.BooleanField(default=False)
    dietDiabetic = models.BooleanField(default=False)
    
    ingestOral = models.BooleanField(default=False)
    ingestFeed = models.BooleanField(default=False)
    ingestParent = models.BooleanField(default=False)
    
    excNoImp = models.BooleanField(default=False)
    excIncont = models.BooleanField(default=False)
    excIncrease = models.BooleanField(default=False)
    excBladder = models.BooleanField(default=False)
    
    bowelNoImp = models.BooleanField(default=False)
    bowelIncon = models.BooleanField(default=False)
    bowelDiarr = models.BooleanField(default=False)
    bowelCons = models.BooleanField(default=False)
    bowelPraetor = models.BooleanField(default=False)
    bowelLax = models.BooleanField(default=False)
    bowelAids = models.BooleanField(default=False)
    
    painNo = models.BooleanField(default=False)
    painYes = models.BooleanField(default=False)
    painPart1 = models.CharField(max_length=240, blank=True, default='')
    painSide1 = models.CharField(max_length=240, blank=True, default='')
    painState1 = models.CharField(max_length=240, blank=True, default='')
    painRest1 = models.CharField(max_length=240, blank=True, default='')
    painExc1 = models.CharField(max_length=240, blank=True, default='')
    painFreq1 = models.CharField(max_length=240, blank=True, default='')
    painType1 = models.CharField(max_length=240, blank=True, default='')
    painPart2 = models.CharField(max_length=240, blank=True, default='')
    painSide2 = models.CharField(max_length=240, blank=True, default='')
    painState2 = models.CharField(max_length=240, blank=True, default='')
    painRest2 = models.CharField(max_length=240, blank=True, default='')
    painExc2 = models.CharField(max_length=240, blank=True, default='')
    painFreq2 = models.CharField(max_length=240, blank=True, default='')
    painType2 = models.CharField(max_length=240, blank=True, default='')
    painPart3 = models.CharField(max_length=240, blank=True, default='')
    painSide3 = models.CharField(max_length=240, blank=True, default='')
    painState3 = models.CharField(max_length=240, blank=True, default='')
    painRest3 = models.CharField(max_length=240, blank=True, default='')
    painExc3 = models.CharField(max_length=240, blank=True, default='')
    painFreq3 = models.CharField(max_length=240, blank=True, default='')
    painType3 = models.CharField(max_length=240, blank=True, default='')
    
    substNo = models.BooleanField(default=False)
    substYes = models.BooleanField(default=False)
    substSmoker = models.BooleanField(default=False)
    substSmokerNr = models.CharField(max_length=240, blank=True, default='')
    substFormer = models.BooleanField(default=False)
    substAlcohol = models.BooleanField(default=False)
    substAlcoholReg = models.BooleanField(default=False)
    substAlcoholOcc = models.BooleanField(default=False)
    substNarc = models.BooleanField(default=False)
    
    ulcersNo = models.BooleanField(default=False)
    ulcersYes = models.BooleanField(default=False)
    ulcersWoundNo = models.BooleanField(default=False)
    ulcersWoundYes = models.BooleanField(default=False)
    
    skinNoFind = models.BooleanField(default=False)
    skinWithFind = models.BooleanField(default=False)
    skinDry = models.BooleanField(default=False)
    skinMoist = models.BooleanField(default=False)
    skinDerm = models.BooleanField(default=False)
    skinParch = models.BooleanField(default=False)
    skinHema = models.BooleanField(default=False)
    
    careDressSelf = models.BooleanField(default=False)
    careDressSupp = models.BooleanField(default=False)
    careFoodSelf = models.BooleanField(default=False)
    careFoodSupp = models.BooleanField(default=False)
    careExcSelf = models.BooleanField(default=False)
    careExcSup = models.BooleanField(default=False)
    careWalkSelf = models.BooleanField(default=False)
    careWalkSupp = models.BooleanField(default=False)
    
    objNo = models.BooleanField(default=False)
    objYes = models.BooleanField(default=False)
    objCompress = models.BooleanField(default=False)
    objDevice = models.BooleanField(default=False)
    objOrtho = models.BooleanField(default=False)
    objPros = models.BooleanField(default=False)
    objOthers = models.CharField(max_length=240, blank=True, default='')
    
    skinIntact = models.BooleanField(default=False)
    skinNotInt = models.BooleanField(default=False)
    skinNotAsc = models.BooleanField(default=False)
    
    inletsNo = models.BooleanField(default=False)
    inletsYes = models.BooleanField(default=False)
    inletsPortYes = models.BooleanField(default=False)
    inletsPortNo = models.BooleanField(default=False)
    inletsProbesYes = models.BooleanField(default=False)
    inletsProbesNo = models.BooleanField(default=False)
    inletsUrineYes = models.BooleanField(default=False)
    inletsUrineNo = models.BooleanField(default=False)
    
    stomataYes = models.BooleanField(default=False)
    stomataNo = models.BooleanField(default=False)
    
    fallNo = models.BooleanField(default=False)
    fallYes = models.BooleanField(default=False)
    fall1x = models.BooleanField(default=False)
    fall2x = models.BooleanField(default=False)
    fall3x = models.BooleanField(default=False)
    fallMore = models.BooleanField(default=False)
    
    drugsNo = models.BooleanField(default=False)
    drugsYes = models.BooleanField(default=False)
    
    diagnoseSync = models.BooleanField(default=False)
    diagnoseEpil = models.BooleanField(default=False)
    diagnoseHunt = models.BooleanField(default=False)
    diagnoseDiab = models.BooleanField(default=False)
    diagnoseNo = models.BooleanField(default=False)
    
    allergyNo = models.BooleanField(default=False)
    allergyYes = models.BooleanField(default=False)
    allergyKnown1 = models.CharField(max_length=240, blank=True, default='')
    allergyKnown2 = models.CharField(max_length=240, blank=True, default='')
    allergyKnown3 = models.CharField(max_length=240, blank=True, default='')
    
    valuablesYes = models.BooleanField(default=False)
    valuablesNo = models.BooleanField(default=False)
    valuablesRel = models.BooleanField(default=False)
    valuablesWard = models.BooleanField(default=False)
    
    informYes = models.BooleanField(default=False)
    informNo = models.BooleanField(default=False)
    
class FormSummary(models.Model):
    content = models.CharField(max_length=15000, blank=True, default='')
    admissionFormFk = models.ForeignKey(AdmissionForm, on_delete=models.CASCADE)
    
class FormSummaryDto(models.Model):
    content = models.CharField(max_length=5000, blank=True, default='')
    admissionFormFk = models.IntegerField()
    
class TranslateType(models.Model):
    language = models.CharField(max_length=100, blank=True, default='')
    summary1 = models.CharField(max_length=5000, blank=True, default='')
    summary2 = models.CharField(max_length=5000, blank=True, default='')
    summary3 = models.CharField(max_length=5000, blank=True, default='')
