from rest_framework import serializers 
from tutorials.models import *
        
class AdmissionFormSerializer(serializers.ModelSerializer):
    
    class Meta:
        model = AdmissionForm
        fields = ('id',
                  'patientFname',
                  'patientLname',
                              'medDrug1',
            'medDosage1',
            'medMorning1',
            'medNoon1',
            'medEvening1',
            'medNight1',
            'medDrug2',
            'medDosage2',
            'medMorning2',
            'medNoon2',
            'medEvening2',
            'medNight2',
            'medDrug3',
            'medDosage3',
            'medMorning3',
            'medNoon3',
            'medEvening3',
            'medNight3',
                  'weight',
                  'height',
                  'liveAloneNo',
                  'liveAloneYes',
                  'liveAloneLift',
                  'liveAloneFloor',
                  'obliationsNo',
                  'obliationsYes',
                  'relativeSurname1',
                  'relativeFname1',
                  'relativePhone1',
                  'relativeRel1',
                  'relativeSurname2',
                  'relativeFname2',
                  'relativePhone2',
                  'relativeRel2',
                  'relativeSurname3',
                  'relativeFname3',
                  'relativePhone3',
                  'relativeRel3',
                  'careNo',
                  'careYes',
                  'careDegree1',
                  'careDegree2',
                  'careDegree3',
                  'careDegree4',
                  'careDegree5',
                  'hospitalizedNo',
                  'hospitalizedYes',
                  'hospAbroadPlace',
                  'hospAbroadTime',
                  'commNoImpairment',
                  'commForeignLang',
                  'commForeignLangYes',
                  'commForeignLangNo',
                  'commSignLang',
                  'commDisorder',
                  'commTrach',
                  'visionLeft',
                  'visionRight',
                  'blindnessLeft',
                  'blindnessRight',
                  'visualAidLeft',
                  'visualAidRight',
                  'hearingNoImp',
                  'hearingAidRight',
                  'hearingAidLeft',
                  'hearingHardRight',
                  'hearingHardLeft',
                  'deafnessRight',
                  'deafnessLeft',
                  'disorNoImp',
                  'disorTime',
                  'disorPlace',
                  'disorPerson',
                  'understNoImp',
                  'understConfusion',
                  'understNerv',
                  'understAltered',
            'disabilityNo',
            'disabilityYes',
            'disabilityHemiYes',
            'disabilityHemi',
            'disabilityAmputYes',
            'disabilityAmput',
            'disabilityParaYes',
            'disabilityPara',
            'disabilityTetraYes',
            'disabilityTetra',
            'disabilityLimbsYes',
            'disabilityLimbs',
            'disabilityMisalYes',
            'disabilityMisal',
            'disabilityProYes',
            'disabilityProNo',
            'sleepNoImp',
            'sleepDiff',
            'sleepBreath',
            'dietWhole',
            'dietNoSugar',
            'dietVeg',
            'dietDiabetic',
            'ingestOral',
            'ingestFeed',
            'ingestParent',
            'excNoImp',
            'excIncont',
            'excIncrease',
            'excBladder',
            'bowelNoImp',
            'bowelIncon',
            'bowelDiarr',
            'bowelCons',
            'bowelPraetor',
            'bowelLax',
            'bowelAids',
            'painNo',
            'painYes',
            'painPart1',
            'painSide1',
            'painState1',
            'painRest1',
            'painExc1',
            'painFreq1',
            'painType1',
            'painPart2',
            'painSide2',
            'painState2',
            'painRest2',
            'painExc2',
            'painFreq2',
            'painType2',
            'painPart3',
            'painSide3',
            'painState3',
            'painRest3',
            'painExc3',
            'painFreq3',
            'painType3',
            'substNo',
            'substYes',
            'substSmoker',
            'substSmokerNr',
            'substFormer',
            'substAlcohol',
            'substAlcoholReg',
            'substAlcoholOcc',
            'substNarc',
            'ulcersNo',
            'ulcersYes',
            'ulcersWoundNo',
            'ulcersWoundYes',
            'skinNoFind',
            'skinWithFind',
            'skinDry',
            'skinMoist',
            'skinDerm',
            'skinParch',
            'skinHema',
            'careDressSelf',
            'careDressSupp',
            'careFoodSelf',
            'careFoodSupp',
            'careExcSelf',
            'careExcSup',
            'careWalkSelf',
            'careWalkSupp',
            'objNo',
            'objYes',
            'objCompress',
            'objDevice',
            'objOrtho',
            'objPros',
            'objOthers',
            'skinIntact',
            'skinNotInt',
            'skinNotAsc',
            'inletsNo',
            'inletsYes',
            'inletsPortYes',
            'inletsPortNo',
            'inletsProbesYes',
            'inletsProbesNo',
            'inletsUrineYes',
            'inletsUrineNo',
            'stomataYes',
            'stomataNo',
            'fallNo',
            'fallYes',
            'fall1x',
            'fall2x',
            'fall3x',
            'fallMore',
            'drugsNo',
            'drugsYes',
            'diagnoseSync',
            'diagnoseEpil',
            'diagnoseHunt',
            'diagnoseDiab',
            'diagnoseNo',
            'allergyNo',
            'allergyYes',
            'allergyKnown1',
            'allergyKnown2',
            'allergyKnown3',
            'valuablesYes',
            'valuablesNo',
            'valuablesRel',
            'valuablesWard',
            'informYes',
            'informNo',
            )
        
class FormSummarySerializer(serializers.ModelSerializer):
 
    class Meta:
        model = FormSummary
        fields = ('id',
                  'content',
                  'admissionFormFk')
        
class FormSummaryDtoSerializer(serializers.ModelSerializer):
 
    class Meta:
        model = FormSummaryDto
        fields = ('id',
                  'content',
                  'admissionFormFk')
        
        
class TranslateTypeSerializer(serializers.ModelSerializer):
 
    class Meta:
        model = TranslateType
        fields = ('id',
                  'language',
                  'summary1',
                  'summary2',
                  'summary3')