# Generated by Django 5.0.2 on 2024-02-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tutorial',
        ),
        migrations.AddField(
            model_name='admissionform',
            name='height',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='patientFname',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='patientLname',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='weight',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
    ]
